# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField(default=6)),
                ('cols', models.IntegerField(default=7)),
                ('board', django.contrib.postgres.fields.jsonb.JSONField(default=[[-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1], [-1, -1, -1, -1, -1, -1, -1]])),
                ('turn', models.IntegerField(default=-1)),
                ('started', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=30)),
                ('total_players', models.IntegerField(default=2)),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('connect', models.IntegerField(default=4)),
                ('next_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_player', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='games', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
