# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 18:31
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='order',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
