# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_auto_20160707_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='connect',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
